export const FETCH_HOMEDATA_REQUEST = "FETCH_HOMEDATA_REQUEST";
export const FETCH_HOMEDATA_REQUEST_SUCCESS = "FETCH_HOMEDATA_REQUEST_SUCCESS";
export const FETCH_HOMEDATA_REQUEST_FAILURE = "FETCH_HOMEDATA_REQUEST_FAILURE";
